### ISSUE TITLE
Program not working properly

### ISSUE THREAD

**Issue by saadpty** [zt2/sqli-hunter#14]
/var/lib/gems/2.7.0/gems/certificate_authority-0.1.6/lib/certificate_authority/certificate.rb:94: warning: constant OpenSSL::Digest::Digest is deprecated
/var/lib/gems/2.7.0/gems/certificate_authority-0.1.6/lib/certificate_authority/certificate.rb:96: warning: constant OpenSSL::Digest::Digest is deprecated

The program just outputs this and than does nothing. 
How to reproduce?

Build the program yourself/install through docker and than run the command including " --targeted-hosts" parameter. 

Edit: I fixed those warnings but now it just stays at [INFO] Proxy server started ... listening on localhost:8080 and does nothing.

**Comment by zt2** [comment]
This warning message from the dependency `certificate_authority`, you can just ignore it.
Have you setup proxy in your browser or mobile?
