### ISSUE TITLE
about https

### ISSUE THREAD

**Issue by Imanfeng** [zt2/sqli-hunter#6]
This is a good project! I found that I can't grab https packets, how can I improve it?

**Comment by Imanfeng** [comment]
s there a way to add a certificate?

**Comment by zt2** [comment]
> s there a way to add a certificate?

Yes, I'm going to build a HTTPS certificate for this project, that could make it capture HTTPS packets

**Comment by Imanfeng** [comment]
cool!

**Comment by zt2** [comment]
HTTPS is now supported in v1.2.0 (https://github.com/zt2/sqli-hunter/commit/65410dda8e2bae6aad38ebc74747bc6727e6de85).
Check out the master branch, please. Any feedbacks are welcome.
